---
- name: List Docker containers
  hosts: all
  gather_facts: false
  vars:
    ansible_stdout_callback: default
    ansible_callback_result_format: yaml
  tasks:
    - name: Get list of running containers
      community.docker.docker_host_info:
            containers: yes
      register: docker_info

    - name: Display container information
      debug:
        msg: |-
          {{ docker_info.containers | map(attribute='Names') | map('first') | map('replace', '/', '') }}