# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Top level entries are assumed to be groups, start with 'all' to have a full hierarchy
#   - Hosts must be specified in a group's hosts:
#     and they must be a key (: terminated)
#   - groups can have children, hosts and vars keys
#   - groups are unique and global - if you define a group in multiple locations, Ansible aggregates all the data to the global name.
#   - If you define a group as a child of 2 different groups, it will be the child of both, any hosts and variables assigned will not be dependent on the parents, they will all be associated with the group.
#   - Anything defined under a host is assumed to be a var
#   - You can enter hostnames or IP addresses
#   - A hostname/IP can be a member of multiple groups
ANSIS_SGP:
    vars:
        ansible_user: root
        postgresql_db_admin: postgres
        postgresql_db_password: wai39kua
        odoo_pw_network: odoo_pw_network
        postgresql_port: 1488
    hosts:
        sg05:
            ansible_host: sg05.ansis.com.sg
            traefik_container: SG05_TRAEFIK
            portainer_container: SG05_PORTAINER
            postgresql_container: SG05DB
            postgresql_docker_image : postgres:16
            postgresql_config_file : postgresql.auto.conf_16GB.j2
            ansible_python_interpreter: /usr/bin/python3
        sg08:
            ansible_host: sg08.ansis.com.sg
            traefik_container: SG08_TRAEFIK
            portainer_container: SG08_PORTAINER
            postgresql_container: SG08DB
            postgresql_docker_image : postgres:16
            postgresql_config_file : postgresql.auto.conf_8GB.j2
            ansible_python_interpreter: /usr/bin/python3
        sg06:
            ansible_host: sg06.ansis.com.sg
            traefik_container: SG06_TRAEFIK
            portainer_container: SG06_PORTAINER
            postgresql_container: SG06_DB            
            ansible_python_interpreter: /usr/bin/python3        

        vars:
            ansible_user: root
            ansible_port: 22
            postgresql_db_admin: postgres
            postgresql_db_password: wai39kua

            
LOCAL:
    hosts:
        localhost:
            ansible_connection: local
            ansible_sudo_pass: Waikuan1@
            portainer_container: LOCAL_PORTAINER
            postgresql_docker_image : postgres:latest
            ansible_python_interpreter: /usr/bin/python3
    vars:
        ansible_user: root
        ansible_port: 8288 
        ansible_python_interpreter: /usr/bin/python3
        postgresql_port: 1488


