---
  - name: Remove the temporary cloned repository
    file:
      path: /tmp/repository
      state: absent

  - name: "Clone the GitHub repository {{ repo.fork_url }} {{ repo.branch }} to /tmp/repository"
    ansible.builtin.shell:
      cmd: git clone {{ repo.fork_url }} --single-branch --branch {{ repo.branch }} --depth 1 repository
      chdir: /tmp

  - name: "Update OCA repositories for {{ repo.fork_url }} {{ repo.branch }}"
    ansible.builtin.shell:
      cmd: rm -rf {{ repo.local_dir }}/{{ include_item }} && cp -r /tmp/repository/{{ include_item }} {{ repo.local_dir }}
    loop: "{{ repo.includes }}"
    loop_control:
      loop_var: include_item  

  - name: Remove the temporary cloned repository
    file:
      path: /tmp/repository
      state: absent