---
- name: Run a gh command to sync {{ repo.fork_url }} at Github repositories from upstream
  ansible.builtin.shell: gh repo sync {{ repo.fork_url }} -b {{ repo.branch }}
  

- name: Ensure the Github repository {{ repo.fork_url }} {{ repo.branch }} is cloned to {{ repo.local_dir }}
  ansible.builtin.git:
    repo: "{{ repo.fork_url }}"
    dest: "{{ repo.local_dir }}"
    version: "{{ repo.branch }}"
    update: true
    force: yes
  when: not ansible_check_mode

# - name: Add upstream remote
#   ansible.builtin.git:
#     repo: "{{ repo.local_dir }}"
#     name: upstream
#     dest: "{{ repo.upstream_url }}"
#   when: not ansible_check_mode

# - name: Fetch changes from {{ repo.fork_url }} to {{ repo.local_dir }}
#   ansible.builtin.git:
#     repo: "{{ repo.fork_url }}"
#     dest: "{{ repo.local_dir }}"
#     update: true
#     version: "{{ repo.branch }}"
#   when: not ansible_check_mode

# - name: Merge changes from upstream into the local branch
#   ansible.builtin.git:
#     repo: "{{ repo.local_dir }}"
#     merge: yes
#     remote: upstream
#     refspec: "{{ repo.branch }}"
#   when: not ansible_check_mode

# - name: Push changes to the forked repository
#   ansible.builtin.git:
#     repo: "{{ repo.local_dir }}"
#     push: yes
#     remote: origin
#     refspec: "{{ repo.branch }}"
#   when: not ansible_check_mode