#SPDX-License-Identifier: MIT-0
---
# tasks file for ssh_connection
  - name: Create variable from command
    command: 'uname -a'
    register: command_output
  - name: Print command output
    debug:
      var: command_output.stdout_lines