#! /usr/local/bin/ansible-playbook
---
- name: Setup Server ( New VPS )
  hosts: all
  become: true

  tasks:
    # Create machine for provision for Digital Ocean Droplet
    # Install all the packages

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install required system packages
      ansible.builtin.apt:
        update_cache: true
        name: "{{ packages }}"
        state: present

      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - python3-pip
          - python3-psycopg2
          - python3-setuptools
          - rsync
          - software-properties-commone
          - virtualenv
          - wget
